-- MySQL Script generated by MySQL Workbench
-- Mon Jul 16 19:16:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema adopt_un_boss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adopt_un_boss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adopt_un_boss` DEFAULT CHARACTER SET utf8 ;
USE `adopt_un_boss` ;

-- -----------------------------------------------------
-- Table `adopt_un_boss`.`techno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`techno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `statut` TINYINT(1) NULL DEFAULT 0,
  `permission` VARCHAR(45) NULL,
  `newsletter` TINYINT(1) NULL DEFAULT 0,
  `message` INT NULL DEFAULT 0,
  `like` INT NULL DEFAULT 0,
  `match` INT NULL DEFAULT 0,
  `visibility` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`entreprise` (
  `user_id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `tel` VARCHAR(20) NULL,
  `adresse` VARCHAR(300) NULL,
  `logo` VARCHAR(4000) NULL,
  `description` VARCHAR(700) NULL,
  `salarie` INT NULL,
  `site_web` VARCHAR(45) NULL,
  `date_creation` DATE NULL,
  `mail` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_entreprise_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `adopt_un_boss`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`offre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entreprise_user_id` INT NOT NULL,
  `intitule` VARCHAR(128) NULL,
  `poste` VARCHAR(96) NULL,
  `lieu` VARCHAR(300) NULL,
  `salaire` VARCHAR(100) NULL,
  `detail` VARCHAR(1024) NULL,
  `date_creation` DATE NULL,
  `statut` TINYINT(1) NULL DEFAULT 0,
  `edition_possible` TINYINT(1) NULL DEFAULT 0,
  `visibility` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`, `entreprise_user_id`),
  INDEX `fk_offre_entreprise1_idx` (`entreprise_user_id` ASC),
  CONSTRAINT `fk_offre_entreprise1`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`candidat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`candidat` (
  `user_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `adresse` VARCHAR(300) NOT NULL,
  `tel` VARCHAR(10) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(4000) NOT NULL,
  `date_creation` DATE NOT NULL,
  `description` VARCHAR(1000) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_candidat_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `adopt_un_boss`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recepteur_id` INT NOT NULL,
  `emetteur_id` INT NOT NULL,
  `contenu` VARCHAR(2048) NULL,
  `date_creation` INT NULL,
  PRIMARY KEY (`id`, `recepteur_id`, `emetteur_id`),
  INDEX `fk_chat_user1_idx` (`emetteur_id` ASC),
  INDEX `fk_chat_user2_idx` (`recepteur_id` ASC),
  CONSTRAINT `fk_chat_user1`
    FOREIGN KEY (`emetteur_id`)
    REFERENCES `adopt_un_boss`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chat_user2`
    FOREIGN KEY (`recepteur_id`)
    REFERENCES `adopt_un_boss`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`admin` (
  `user_id` INT NOT NULL,
  `pseudo` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_admin_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `adopt_un_boss`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`actualite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`actualite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `texte` VARCHAR(1024) NULL,
  `statut` TINYINT(1) NULL DEFAULT 0,
  `date_creation` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(100) NULL,
  `description` VARCHAR(1024) NULL,
  `image` VARCHAR(4000) NULL,
  `lieu` VARCHAR(300) NULL,
  `date` DATE NULL,
  `heure` VARCHAR(5) NULL,
  `statut` TINYINT(1) NULL DEFAULT 0,
  `date_creation` DATE NULL,
  `entreprise_user_id` INT NOT NULL,
  `visibility` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `entreprise_user_id`),
  INDEX `fk_event_entreprise1_idx` (`entreprise_user_id` ASC),
  CONSTRAINT `fk_event_entreprise1`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`candidat_has_techno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`candidat_has_techno` (
  `candidat_user_id` INT NOT NULL,
  `techno_id` INT NOT NULL,
  PRIMARY KEY (`candidat_user_id`, `techno_id`),
  INDEX `fk_candidat_has_techno_techno1_idx` (`techno_id` ASC),
  INDEX `fk_candidat_has_techno_candidat1_idx` (`candidat_user_id` ASC),
  CONSTRAINT `fk_candidat_has_techno_candidat1`
    FOREIGN KEY (`candidat_user_id`)
    REFERENCES `adopt_un_boss`.`candidat` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidat_has_techno_techno1`
    FOREIGN KEY (`techno_id`)
    REFERENCES `adopt_un_boss`.`techno` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`offre_has_techno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`offre_has_techno` (
  `techno_id` INT NOT NULL,
  `offre_id` INT NOT NULL,
  PRIMARY KEY (`techno_id`, `offre_id`),
  INDEX `fk_techno_has_offre_offre1_idx` (`offre_id` ASC),
  INDEX `fk_techno_has_offre_techno1_idx` (`techno_id` ASC),
  CONSTRAINT `fk_techno_has_offre_techno1`
    FOREIGN KEY (`techno_id`)
    REFERENCES `adopt_un_boss`.`techno` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_techno_has_offre_offre1`
    FOREIGN KEY (`offre_id`)
    REFERENCES `adopt_un_boss`.`offre` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`secteur_d_activite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`secteur_d_activite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(40) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`entreprise_has_secteur_d_activite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`entreprise_has_secteur_d_activite` (
  `entreprise_user_id` INT NOT NULL,
  `secteur_d_activite_id` INT NOT NULL,
  PRIMARY KEY (`entreprise_user_id`, `secteur_d_activite_id`),
  INDEX `fk_entreprise_has_secteur_d_activite_secteur_d_activite1_idx` (`secteur_d_activite_id` ASC),
  INDEX `fk_entreprise_has_secteur_d_activite_entreprise1_idx` (`entreprise_user_id` ASC),
  CONSTRAINT `fk_entreprise_has_secteur_d_activite_entreprise1`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entreprise_has_secteur_d_activite_secteur_d_activite1`
    FOREIGN KEY (`secteur_d_activite_id`)
    REFERENCES `adopt_un_boss`.`secteur_d_activite` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`type_de_contrat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`type_de_contrat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_de_contrat` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`offre_has_type_de_contrat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`offre_has_type_de_contrat` (
  `type_de_contrat_id` INT NOT NULL,
  `offre_id` INT NOT NULL,
  PRIMARY KEY (`type_de_contrat_id`, `offre_id`),
  INDEX `fk_type_de_contrat_has_offre_offre1_idx` (`offre_id` ASC),
  INDEX `fk_type_de_contrat_has_offre_type_de_contrat1_idx` (`type_de_contrat_id` ASC),
  CONSTRAINT `fk_type_de_contrat_has_offre_type_de_contrat1`
    FOREIGN KEY (`type_de_contrat_id`)
    REFERENCES `adopt_un_boss`.`type_de_contrat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_type_de_contrat_has_offre_offre1`
    FOREIGN KEY (`offre_id`)
    REFERENCES `adopt_un_boss`.`offre` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`candidat_liked_offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`candidat_liked_offre` (
  `candidat_user_id` INT NOT NULL,
  `offre_id` INT NOT NULL,
  `answered` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`candidat_user_id`, `offre_id`),
  INDEX `fk_candidat_has_offre_offre1_idx` (`offre_id` ASC),
  INDEX `fk_candidat_has_offre_candidat1_idx` (`candidat_user_id` ASC),
  CONSTRAINT `fk_candidat_has_offre_candidat1`
    FOREIGN KEY (`candidat_user_id`)
    REFERENCES `adopt_un_boss`.`candidat` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidat_has_offre_offre1`
    FOREIGN KEY (`offre_id`)
    REFERENCES `adopt_un_boss`.`offre` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`entreprise_liked_candidat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`entreprise_liked_candidat` (
  `entreprise_user_id` INT NOT NULL,
  `candidat_user_id` INT NOT NULL,
  `offre_id` INT NOT NULL,
  PRIMARY KEY (`entreprise_user_id`, `candidat_user_id`, `offre_id`),
  INDEX `fk_entreprise_has_candidat_candidat1_idx` (`candidat_user_id` ASC),
  INDEX `fk_entreprise_has_candidat_entreprise1_idx` (`entreprise_user_id` ASC),
  CONSTRAINT `fk_entreprise_has_candidat_entreprise1`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entreprise_has_candidat_candidat1`
    FOREIGN KEY (`candidat_user_id`)
    REFERENCES `adopt_un_boss`.`candidat` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`candidat_bookmarked_offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`candidat_bookmarked_offre` (
  `candidat_user_id` INT NOT NULL,
  `offre_id` INT NOT NULL,
  PRIMARY KEY (`candidat_user_id`, `offre_id`),
  INDEX `fk_candidat_has_offre_offre2_idx` (`offre_id` ASC),
  INDEX `fk_candidat_has_offre_candidat2_idx` (`candidat_user_id` ASC),
  CONSTRAINT `fk_candidat_has_offre_candidat2`
    FOREIGN KEY (`candidat_user_id`)
    REFERENCES `adopt_un_boss`.`candidat` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidat_has_offre_offre2`
    FOREIGN KEY (`offre_id`)
    REFERENCES `adopt_un_boss`.`offre` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`candidat_viewed_offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`candidat_viewed_offre` (
  `candidat_user_id` INT NOT NULL,
  `offre_id` INT NOT NULL,
  PRIMARY KEY (`candidat_user_id`, `offre_id`),
  INDEX `fk_candidat_has_offre1_offre1_idx` (`offre_id` ASC),
  INDEX `fk_candidat_has_offre1_candidat1_idx` (`candidat_user_id` ASC),
  CONSTRAINT `fk_candidat_has_offre1_candidat1`
    FOREIGN KEY (`candidat_user_id`)
    REFERENCES `adopt_un_boss`.`candidat` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidat_has_offre1_offre1`
    FOREIGN KEY (`offre_id`)
    REFERENCES `adopt_un_boss`.`offre` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`entreprise_viewed_offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`entreprise_viewed_offre` (
  `entreprise_user_id` INT NOT NULL,
  `offre_id` INT NOT NULL,
  PRIMARY KEY (`entreprise_user_id`, `offre_id`),
  INDEX `fk_entreprise_has_offre_offre1_idx` (`offre_id` ASC),
  INDEX `fk_entreprise_has_offre_entreprise1_idx` (`entreprise_user_id` ASC),
  CONSTRAINT `fk_entreprise_has_offre_entreprise1`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entreprise_has_offre_offre1`
    FOREIGN KEY (`offre_id`)
    REFERENCES `adopt_un_boss`.`offre` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`candidat_viewed_entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`candidat_viewed_entreprise` (
  `candidat_user_id` INT NOT NULL,
  `entreprise_user_id` INT NOT NULL,
  PRIMARY KEY (`candidat_user_id`, `entreprise_user_id`),
  INDEX `fk_candidat_has_entreprise_entreprise1_idx` (`entreprise_user_id` ASC),
  INDEX `fk_candidat_has_entreprise_candidat1_idx` (`candidat_user_id` ASC),
  CONSTRAINT `fk_candidat_has_entreprise_candidat1`
    FOREIGN KEY (`candidat_user_id`)
    REFERENCES `adopt_un_boss`.`candidat` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidat_has_entreprise_entreprise1`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`entreprise_viewed_candidat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`entreprise_viewed_candidat` (
  `entreprise_user_id` INT NOT NULL,
  `candidat_user_id` INT NOT NULL,
  PRIMARY KEY (`entreprise_user_id`, `candidat_user_id`),
  INDEX `fk_entreprise_has_candidat_candidat2_idx` (`candidat_user_id` ASC),
  INDEX `fk_entreprise_has_candidat_entreprise2_idx` (`entreprise_user_id` ASC),
  CONSTRAINT `fk_entreprise_has_candidat_entreprise2`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entreprise_has_candidat_candidat2`
    FOREIGN KEY (`candidat_user_id`)
    REFERENCES `adopt_un_boss`.`candidat` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`event_has_candidat_participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`event_has_candidat_participant` (
  `event_id` INT NOT NULL,
  `candidat_user_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `candidat_user_id`),
  INDEX `fk_event_has_candidat_candidat1_idx` (`candidat_user_id` ASC),
  INDEX `fk_event_has_candidat_event1_idx` (`event_id` ASC),
  CONSTRAINT `fk_event_has_candidat_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `adopt_un_boss`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_event_has_candidat_candidat1`
    FOREIGN KEY (`candidat_user_id`)
    REFERENCES `adopt_un_boss`.`candidat` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`event_has_entreprise_participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`event_has_entreprise_participant` (
  `event_id` INT NOT NULL,
  `entreprise_user_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `entreprise_user_id`),
  INDEX `fk_event_has_entreprise_entreprise1_idx` (`entreprise_user_id` ASC),
  INDEX `fk_event_has_entreprise_event1_idx` (`event_id` ASC),
  CONSTRAINT `fk_event_has_entreprise_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `adopt_un_boss`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_event_has_entreprise_entreprise1`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`entreprise_viewed_entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`entreprise_viewed_entreprise` (
  `entreprise_user_id` INT NOT NULL,
  `entreprise_user_id1` INT NOT NULL,
  PRIMARY KEY (`entreprise_user_id`, `entreprise_user_id1`),
  INDEX `fk_entreprise_has_entreprise_entreprise2_idx` (`entreprise_user_id1` ASC),
  INDEX `fk_entreprise_has_entreprise_entreprise1_idx` (`entreprise_user_id` ASC),
  CONSTRAINT `fk_entreprise_has_entreprise_entreprise1`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entreprise_has_entreprise_entreprise2`
    FOREIGN KEY (`entreprise_user_id1`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`matching`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`matching` (
  `candidat_user_id` INT NOT NULL,
  `entreprise_user_id` INT NOT NULL,
  `offre_id` INT NOT NULL,
  PRIMARY KEY (`candidat_user_id`, `entreprise_user_id`),
  INDEX `fk_candidat_has_entreprise_entreprise2_idx` (`entreprise_user_id` ASC),
  INDEX `fk_candidat_has_entreprise_candidat2_idx` (`candidat_user_id` ASC),
  CONSTRAINT `fk_candidat_has_entreprise_candidat2`
    FOREIGN KEY (`candidat_user_id`)
    REFERENCES `adopt_un_boss`.`candidat` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidat_has_entreprise_entreprise2`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_un_boss`.`candidat_and_entreprise_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_un_boss`.`candidat_and_entreprise_chat` (
  `candidat_user_id` INT NOT NULL,
  `entreprise_user_id` INT NOT NULL,
  `message_entreprise` INT NULL,
  `message_candidat` INT NULL,
  PRIMARY KEY (`candidat_user_id`, `entreprise_user_id`),
  INDEX `fk_candidat_has_entreprise_entreprise3_idx` (`entreprise_user_id` ASC),
  INDEX `fk_candidat_has_entreprise_candidat3_idx` (`candidat_user_id` ASC),
  CONSTRAINT `fk_candidat_has_entreprise_candidat3`
    FOREIGN KEY (`candidat_user_id`)
    REFERENCES `adopt_un_boss`.`candidat` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidat_has_entreprise_entreprise3`
    FOREIGN KEY (`entreprise_user_id`)
    REFERENCES `adopt_un_boss`.`entreprise` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
